# Generated by Django 3.1.3 on 2020-12-22 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0012_auto_20201222_2118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopuser',
            name='activation_key_expires',
        ),
    ]
