# Generated by Django 3.1.3 on 2020-12-22 21:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0013_remove_shopuser_activation_key_expires'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 24, 21, 20, 38, 668615, tzinfo=utc)),
        ),
    ]
